<a href="https://colab.research.google.com/github/shanthivijayan/Python_Code/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
# import numpy library

import numpy as np
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])
print(np.__version__)
# Check the type of the array

type(a)
# Check the type of the values stored in numpy array

a.dtype
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c
# Assign the first element to 100

c[0] = 100
c
# Slicing the numpy array

d = c[1:4]
d
# Set the fourth element and fifth element to 300 and 400

c[3:5] = 300, 400
c
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])#[start:end:step]
print(arr[:4])#If we don't pass start its considered 0
print(arr[4:])#If we don't pass end it considers till the length of array.
print(arr[1:5:])#If we don't pass step its considered 1
#Print the even elements in the given array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# Enter your code here
print(arr[1:8:2])
# Get the size of numpy array
a.size
# Get the number of dimensions of numpy array
a.ndim
# Get the shape/size of numpy array
a.shape
#Numpy Statistical Functions
# Get the mean of numpy array
mean = a.mean()
mean
# Get the standard deviation of numpy array
standard_deviation=a.std()
standard_deviation
# Get the biggest value in the numpy array
max_a = a.max()
max_a
# Get the smallest value in the numpy array
min_a = a.min()
min_a
#Numpy Array Operations
u = np.array([1, 0])
v = np.array([0, 1])
# Numpy Array Addition
z = np.add(u, v)
z
# Numpy Array Subtraction
z = np.subtract(u, v)
z
# Numpy Array Mulitiplication
z = np.multiply(u, v)
z
# Numpy Array Division
a=[6,8]
b=[2,4]
c = np.divide(a, b)
c
#dot product multiply the vaules and add those values provide single value
X = np.array([1, 2])
Y = np.array([3, 2])
# Calculate the dot product
np.dot(X, Y)
#Elements of X
print(X[0])
print(X[1])
#Linspace returns evenly spaced numbers over a specified interval.
# Makeup a numpy array within [-2, 2] and 5 elements
np.linspace(-2, 2, num=5)

# Make a numpy array within [-2, 2] and 9 elements
print(np.linspace(-2, 2, num=9))
#Adding Constant to a Numpy Array
# Create a constant to numpy array
u = np.array([1, 2, 3, -1])
# Add the constant to array
u + 5
#Mathematical Functions
# The value of pi
print(np.pi)
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

#Starting index in slice is 1 as first even element(2) in array1 is at index 1
even_arr1 = arr1[1:5:2]
print("even for array1",even_arr1)

#Starting index in slice is 0 as first odd element(1) in array1 is at index 0
odd_arr1=arr1[0:5:2]
print("odd for array1",odd_arr1)

#Starting index in slice is 0 as first even element(6) in array2 is at index 0
even_arr2 = arr2[0:5:2]
print("even for array2",even_arr2)


#Starting index in slice is 1 as first odd element(7) in array2 is at index 1
odd_arr2=arr2[1:5:2]
print("odd for array2",odd_arr2)

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4
1.25.2
[2 4]
[1 2 3 4]
[5 6 7]
[2 3 4 5]
[2 4 6 8]
1
2
[-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2. ]
3.141592653589793
even for array1 [2 4]
odd for array1 [1 3 5]
even for array2 [ 6  8 10]
odd for array2 [7 9]


What is Numpy?
NumPy is a Python library used for working with arrays, linear algebra, fourier transform, and matrices. NumPy stands for Numerical Python and it is an open source project. The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

NumPy is usually imported under the np alias.