<a href="https://colab.research.google.com/github/shanthivijayan/Python_Code/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
# import numpy library

import numpy as np
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])
print(np.__version__)
# Check the type of the array

type(a)
# Check the type of the values stored in numpy array

a.dtype
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c
# Assign the first element to 100

c[0] = 100
c
# Slicing the numpy array

d = c[1:4]
d
# Set the fourth element and fifth element to 300 and 400

c[3:5] = 300, 400
c
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])#[start:end:step]
print(arr[:4])#If we don't pass start its considered 0
print(arr[4:])#If we don't pass end it considers till the length of array.
print(arr[1:5:])#If we don't pass step its considered 1
#Print the even elements in the given array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# Enter your code here
print(arr[1:8:2])


a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4
1.25.2
[2 4]
[1 2 3 4]
[5 6 7]
[2 3 4 5]
[2 4 6 8]
