<a href="https://colab.research.google.com/github/shanthivijayan/Python_Code/blob/main/Python_2D_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
# Import the libraries

import numpy as np
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
print(A)
# Show the numpy array dimensions(Number of axes or dimensions)

print("dimension",A.ndim)
# Show the numpy array shape(number of each dimension)

print("Shape",A.shape)
# Show the numpy array size(total number of elements in the array)

print("Size",A.size)
# Access the element on the second row and third column

print(A[1, 2])
# Access the element on the second row and third column

print(A[1][2])
# Access the element on the first row and first and second columns

A[0][0:2]
# Access the element on the first and second rows and third column

A[0:2, 2]
 #Create a numpy array X

X = np.array([[1, 0], [0, 1]])
X
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]])
Y
# Add X and Y

Z = X + Y
print("Addition",Z)
# Multiply Y with 2

Z = 2 * Y
print(" 2 * Y",Z)
# Multiply X with Y

Z = X * Y
print("x*y",Z)
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B
# Calculate the dot product

Z = np.dot(A,B)
print("np.dot(A,B)",Z)
# Calculate the sine of Z

print("np.sin(Z)",np.sin(Z))
#We use the numpy attribute T to calculate the transposed matrix
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C
# Get the transposed of C

C.T

[[11 12 13]
 [21 22 23]
 [31 32 33]]
dimension 2
Shape (3, 3)
Size 9
23
23
Addition [[3 1]
 [1 3]]
 2 * Y [[4 2]
 [2 4]]
x*y [[2 0]
 [0 2]]
np.dot(A,B) [[0 2]
 [0 2]]
np.sin(Z) [[0.         0.90929743]
 [0.         0.90929743]]


array([[1, 2, 3],
       [1, 2, 3]])